# سيرفر تجربة ACRPJobs - عالم مسطّح، بدون وحوش، كرييتف.
# كل مناطق ونقاط التجربة موضوعة حول (0, 4, 0).
level-name=world
level-type=FLAT
generate-structures=false
gamemode=1
force-gamemode=true
difficulty=0
spawn-monsters=false
spawn-animals=false
spawn-npcs=false
pvp=false
allow-nether=false
max-players=10
view-distance=8
online-mode=true
white-list=false
motd=§bACRP §7| §fسيرفر تجربة نظام الوظائف
server-port=25565
enable-command-block=false
allow-flight=true
